
from google.adk.agents import Agent
from prompt import CONTENT_CREATION_AGENT_INSTRUCTIONS
from dotenv import load_dotenv
import os

load_dotenv()

content_creation_agent = Agent(
    model="gemini-2.5-flash",
    name="content_creation_agent",
    description="This is the Content Creation Agent responsible for writing the actual content based on a structured plan. The Content Creation Agent takes the plan generated by the Planning Agent and creates the actual content — for example, the text of a LinkedIn post, a short video script, or a blog intro.",
    instruction=CONTENT_CREATION_AGENT_INSTRUCTIONS,
)